name: "Test Ephemeral Runners"

on:
  push:
    branches: [ "main" ]

jobs:
  ephemeral-runner-job:
    runs-on: 
      - self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Hello ephemeral runner
        run: echo "Hello from an ephemeral runners!"
