name: "Test Ephemeral Runners"

on:
  workflow_dispatch:
    inputs:
      sleep_duration:
        description: "How long to sleep (in seconds)"
        required: false
        default: "15"

jobs:
  ephemeral-runner-job:
    runs-on: punit-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Hello ephemeral runner
        run: |
          echo "Hello from a punit runner!"
          echo "Sleeping for ${{ github.event.inputs.sleep_duration }} seconds..."
          sleep ${{ github.event.inputs.sleep_duration }}
