name: "Test Job Failure"

on:
  workflow_dispatch:

jobs:
  fail-job:
    runs-on: punit-runner  # or any runner you use
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Intentionally fail the job
        run: |
          echo "This job will fail now..."
          exit 1
